version: '3.9'

services:
  python:
    container_name: backend-frontend
    build: .
    ports:
      - "5000:5000"

  db:
    container_name: sqlite-db
    build: .
    volumes:
      - ./app:/db
    environment:
      - DATABASE_CLIENT = sqlite
      - DATABASE_FILENAME = ./instance/web-site.db